ALTER TABLE paradas ADD CONSTRAINT par_fk_tip FOREIGN KEY (id_tipo_parada) REFERENCES tipos_paradas (id_tipo_parada) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE paradas ADD CONSTRAINT par_fk_idr FOREIGN KEY (id_ruta) REFERENCES rutas (id_ruta) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE paradas ADD CONSTRAINT par_fk_ide FOREIGN KEY (id_estacion) REFERENCES estaciones (id_estacion) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE paradas ADD CONSTRAINT par_fk_idpa FOREIGN KEY (id_paradero) REFERENCES paraderos (id_paradero) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE paradas ADD CONSTRAINT par_fk_idpo FOREIGN KEY (id_portal) REFERENCES portales (id_portal) ON DELETE CASCADE ON UPDATE CASCADE;
